# Generated by Django 4.0.3 on 2022-05-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rank',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
