# Generated by Django 4.0.3 on 2022-05-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='glimpse',
        ),
    ]
